package pdf

import (
	"bytes"
	"fmt"

	"github.com/jung-kurt/gofpdf"
)

// InvoiceData is the minimal set of fields rendered on a customer invoice PDF.
type InvoiceData struct {
	DocumentRef string
	CustomerRef string
	Description string
	Amount      string
	AmountPaid  string
	Currency    string
	Status      string
	DueDate     string
	IssuedAt    string
}

// RenderInvoice builds a simple A4 invoice PDF.
func RenderInvoice(d InvoiceData) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(18, 18, 18)
	pdf.AddPage()
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(0, 10, "TAX INVOICE")
	pdf.Ln(12)
	pdf.SetFont("Arial", "", 11)
	pdf.Cell(0, 7, fmt.Sprintf("Invoice: %s", d.DocumentRef))
	pdf.Ln(7)
	pdf.Cell(0, 7, fmt.Sprintf("Customer: %s", d.CustomerRef))
	pdf.Ln(7)
	if d.IssuedAt != "" {
		pdf.Cell(0, 7, fmt.Sprintf("Issued: %s", d.IssuedAt))
		pdf.Ln(7)
	}
	if d.DueDate != "" {
		pdf.Cell(0, 7, fmt.Sprintf("Due: %s", d.DueDate))
		pdf.Ln(7)
	}
	pdf.Ln(4)
	pdf.SetFont("Arial", "B", 11)
	pdf.Cell(120, 8, "Description")
	pdf.Cell(30, 8, "Amount")
	pdf.Cell(0, 8, "Status")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 11)
	desc := d.Description
	if desc == "" {
		desc = "Goods / services"
	}
	pdf.Cell(120, 8, desc)
	pdf.Cell(30, 8, fmt.Sprintf("%s %s", d.Currency, d.Amount))
	pdf.Cell(0, 8, d.Status)
	pdf.Ln(12)
	pdf.SetFont("Arial", "B", 12)
	balance := d.Amount
	if d.AmountPaid != "" && d.AmountPaid != "0" && d.AmountPaid != "0.00" {
		pdf.Cell(0, 8, fmt.Sprintf("Paid: %s %s", d.Currency, d.AmountPaid))
		pdf.Ln(8)
	}
	pdf.Cell(0, 8, fmt.Sprintf("Balance due: %s %s", d.Currency, balance))
	pdf.Ln(10)
	pdf.SetFont("Arial", "I", 9)
	pdf.MultiCell(0, 5, "Generated by IAG Finance. Fiscalise via URA EFRIS before delivery where required.", "", "L", false)

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
