-- Intentionally empty.
--
-- This file used to write pre-rendered demo rows into table_rows under the table_ids
-- 'seed_coa', 'seed_bank_cash', 'seed_ap_inbox' and 'seed_cherry_intake'. They were
-- removed from every environment by migration 068_purge_demo_seed.sql and must not
-- come back: the finance views now render whatever the service actually holds.
--
-- The file is kept rather than deleted so the //go:embed directive in internal/db/db.go
-- still resolves. RunDemoSeed executes it as a comment-only statement — a no-op.
