-- Intentionally empty.
--
-- This file used to write the demo bank accounts (1110/1120/1130), the AP inbox
-- placeholders and the cherry-intake lines that backed the same views. They were
-- removed from every environment by migration 068_purge_demo_seed.sql.
--
-- Real bank accounts, payables and intake lines are created through the service.
--
-- The file is kept rather than deleted so the //go:embed directive in internal/db/db.go
-- still resolves. RunOperationalSeed executes it as a comment-only statement — a no-op.
